on:
  push:
    branches: [emacs-git-latest]
  pull_request:

name: CI

env:
  FLATPAK_BUILDER_N_JOBS: 8

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: emacs.flatpak
        manifest-path: org.gnu.emacs.yml
        cache-key: flatpak-builder-${{ github.sha }}
